// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApz5Ysm9SdKh8cyG0llOzAnXzoMK6qIeA',
    appId: '1:613371430044:web:4ec8a9a433725aec2f5959',
    messagingSenderId: '613371430044',
    databaseURL: "https://sailwatch-48901-default-rtdb.asia-southeast1.firebasedatabase.app",
    projectId: 'sailwatch-48901',
    authDomain: 'sailwatch-48901.firebaseapp.com',
    storageBucket: 'sailwatch-48901.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGnS0sO6KXRKL-k1Eb8WJJOAebLQYMLyw',
    appId: '1:613371430044:android:f4b607b72c3c58032f5959',
    messagingSenderId: '613371430044',
    databaseURL: "https://sailwatch-48901-default-rtdb.asia-southeast1.firebasedatabase.app",
    projectId: 'sailwatch-48901',
    storageBucket: 'sailwatch-48901.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2O9DUAsu66wDk3eV-BY3jly0yDHwQp9E',
    appId: '1:613371430044:ios:8300e84d6700b0752f5959',
    messagingSenderId: '613371430044',
    databaseURL: "https://sailwatch-48901-default-rtdb.asia-southeast1.firebasedatabase.app",
    projectId: 'sailwatch-48901',
    storageBucket: 'sailwatch-48901.appspot.com',
    iosBundleId: 'com.example.sailwatchMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2O9DUAsu66wDk3eV-BY3jly0yDHwQp9E',
    appId: '1:613371430044:ios:8300e84d6700b0752f5959',
    messagingSenderId: '613371430044',
    databaseURL: "https://sailwatch-48901-default-rtdb.asia-southeast1.firebasedatabase.app",
    projectId: 'sailwatch-48901',
    storageBucket: 'sailwatch-48901.appspot.com',
    iosBundleId: 'com.example.sailwatchMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApz5Ysm9SdKh8cyG0llOzAnXzoMK6qIeA',
    appId: '1:613371430044:web:3022c875c974aa472f5959',
    messagingSenderId: '613371430044',
    databaseURL: "https://sailwatch-48901-default-rtdb.asia-southeast1.firebasedatabase.app",
    projectId: 'sailwatch-48901',
    authDomain: 'sailwatch-48901.firebaseapp.com',
    storageBucket: 'sailwatch-48901.appspot.com',
  );
}
